name: Launch DK_OK_bot3

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 */6 * * *"

env:
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  NODE_VERSION: latest
jobs:
  launch-dk-ok-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - name: Setup DK_OK_bot
      run: npm install
    - name: Run DK_OK_bot
      continue-on-error: true
      run: node DK_OK_bot.js
